/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CountDown: typeof import('./src/components/CountDown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HumanHeader: typeof import('./src/components/HumanHeader.vue')['default']
    IconError: typeof import('./src/components/IconError.vue')['default']
    IconInfo: typeof import('./src/components/IconInfo.vue')['default']
    IconSuccess: typeof import('./src/components/IconSuccess.vue')['default']
    Languge: typeof import('./src/components/Languge.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetPassword: typeof import('./src/components/SetPassword.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    SvgTemp: typeof import('./src/components/SvgTemp.vue')['default']
    TextWrapper: typeof import('./src/components/TextWrapper.vue')['default']
    ThemeColorsTest: typeof import('./src/components/ThemeColorsTest.vue')['default']
    UploadWithCropper: typeof import('./src/components/UploadWithCropper.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
